version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - ENVIRONMENT=production
      - CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
      - AZURE_SQL_SERVER=${AZURE_SQL_SERVER}
      - AZURE_SQL_DATABASE=${AZURE_SQL_DATABASE}
      - COSMOS_ENDPOINT=${COSMOS_ENDPOINT}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GROK_API_KEY=${GROK_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - AMAP_API_KEY=${AMAP_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./logs:/var/log/nginx
    networks:
      - app-network
    depends_on:
      - cache

  cache:
    image: redis:alpine
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 